//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobil
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DailySheet
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Day { get; set; }
        public Nullable<decimal> Tank_one_dip { get; set; }
        public Nullable<decimal> Tank_two_dip { get; set; }
        public Nullable<decimal> Tank_three_dip { get; set; }
        public Nullable<decimal> Tank_four_dip { get; set; }
        public Nullable<decimal> Tank_five_dip { get; set; }
        public Nullable<decimal> Tank_six_dip { get; set; }
        public Nullable<decimal> TF_price_e10 { get; set; }
        public Nullable<decimal> TF_price_91 { get; set; }
        public Nullable<decimal> TF_price_98 { get; set; }
        public Nullable<decimal> TF_price_Diesel { get; set; }
        public Nullable<decimal> TLS_e10 { get; set; }
        public Nullable<decimal> TLS_91 { get; set; }
        public Nullable<decimal> TLS_98 { get; set; }
        public Nullable<decimal> TLS_Diesel { get; set; }
        public Nullable<decimal> TD_e10 { get; set; }
        public Nullable<decimal> TD_91 { get; set; }
        public Nullable<decimal> TD_98 { get; set; }
        public Nullable<decimal> TD_Diesel { get; set; }
        public Nullable<decimal> TLS_Total { get; set; }
        public Nullable<decimal> TD_Total { get; set; }
        public Nullable<decimal> HotFood { get; set; }
        public Nullable<decimal> Pai { get; set; }
        public Nullable<decimal> ColdFood { get; set; }
        public Nullable<decimal> Coffee { get; set; }
        public decimal TotalHotFood { get; set; }
        public decimal Total_efpost { get; set; }
        public Nullable<decimal> E_efpost { get; set; }
        public Nullable<decimal> MotorPass { get; set; }
        public Nullable<decimal> MotorCharge { get; set; }
        public Nullable<decimal> FleetCard { get; set; }
        public decimal SafeDrop { get; set; }
        public Nullable<decimal> CashPaidout { get; set; }
        public Nullable<decimal> Accounts { get; set; }
        public decimal Total { get; set; }
        public decimal TotalSale { get; set; }
        public decimal Shopsale { get; set; }
        public Nullable<decimal> Cigartte { get; set; }
        public Nullable<decimal> E_pay { get; set; }
        public Nullable<decimal> Refund { get; set; }
        public Nullable<decimal> MISC { get; set; }
        public Nullable<decimal> ATMFilled { get; set; }
        public decimal Diffrence { get; set; }
    }
}
