//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobil
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public long UID { get; set; }
        public Nullable<long> UserTypeID { get; set; }
        public string UName { get; set; }
        public string UPass { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
    
        public virtual tbl_UserType tbl_UserType { get; set; }
    }
}
