//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobil
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserType
    {
        public tbl_UserType()
        {
            this.tbl_User = new HashSet<tbl_User>();
        }
    
        public long UserTypeID { get; set; }
        public string UserType { get; set; }
    
        public virtual ICollection<tbl_User> tbl_User { get; set; }
    }
}
